import { ITransaction } from './types';

// All existing spreadsheet data converted to seed format
export const SEED_DATA: Omit<ITransaction, '_id' | 'balanceOwed' | 'status' | 'createdAt' | 'updatedAt'>[] = [
  // === May 1, 2026 ===
  {
    date: '2026-05-01',
    type: 'INCOME',
    category: 'Rooms',
    description: 'Lodge - Customer 1 (Room 1) Night',
    totalCharged: 15000,
    amountPaid: 15000,
    stayType: 'Night',
    roomNumber: 1,
  },
  {
    date: '2026-05-01',
    type: 'INCOME',
    category: 'Rooms',
    description: 'Lodge - Customer 2 (Room 4) Short',
    totalCharged: 5000,
    amountPaid: 5000,
    stayType: 'Short',
    roomNumber: 4,
  },
  {
    date: '2026-05-01',
    type: 'INCOME',
    category: 'Rooms',
    description: 'Lodge - (Pastor) (Room 4)',
    totalCharged: 10000,
    amountPaid: 10000,
    stayType: 'Night',
    roomNumber: 4,
  },
  {
    date: '2026-05-01',
    type: 'EXPENSE',
    category: 'Utilities',
    description: 'SLTV Sub 1 Month',
    totalCharged: 5000,
    amountPaid: 5000,
  },
  {
    date: '2026-05-01',
    type: 'EXPENSE',
    category: 'Supplies',
    description: 'Soap & Toiletries',
    totalCharged: 500,
    amountPaid: 500,
  },
  {
    date: '2026-05-01',
    type: 'EXPENSE',
    category: 'Utilities',
    description: 'Gas Cylinder Fill - Generator',
    totalCharged: 16000,
    amountPaid: 16000,
  },
  {
    date: '2026-05-01',
    type: 'EXPENSE',
    category: 'Bar',
    description: 'Packet of Bottle Water',
    totalCharged: 2900,
    amountPaid: 2900,
  },
  {
    date: '2026-05-01',
    type: 'INCOME',
    category: 'Bar',
    description: 'Bottle of Water',
    totalCharged: 500,
    amountPaid: 500,
  },
  // === May 2, 2026 ===
  {
    date: '2026-05-02',
    type: 'EXPENSE',
    category: 'Utilities',
    description: 'Gas fill 12kg',
    totalCharged: 15000,
    amountPaid: 15000,
  },
  {
    date: '2026-05-02',
    type: 'EXPENSE',
    category: 'Supplies',
    description: 'Soap & Toiletries',
    totalCharged: 750,
    amountPaid: 750,
  },
  {
    date: '2026-05-02',
    type: 'INCOME',
    category: 'Bar',
    description: 'Bottle of Water Small',
    totalCharged: 400,
    amountPaid: 400,
  },
  {
    date: '2026-05-02',
    type: 'EXPENSE',
    category: 'Bar',
    description: 'Drinks (6 malts-33) (Half Crate Minera-33)',
    totalCharged: 6800,
    amountPaid: 6800,
  },
  {
    date: '2026-05-02',
    type: 'INCOME',
    category: 'Rooms',
    description: 'Lodge - Jiro (Room 2) Night',
    totalCharged: 15000,
    amountPaid: 15000,
    stayType: 'Night',
    roomNumber: 2,
  },
  {
    date: '2026-05-02',
    type: 'EXPENSE',
    category: 'Salaries',
    description: 'Chidera Stipend',
    totalCharged: 3500,
    amountPaid: 3500,
  },
  {
    date: '2026-05-02',
    type: 'INCOME',
    category: 'Rooms',
    description: 'Lodge (Lupenz) (Short) Room 4',
    totalCharged: 5000,
    amountPaid: 5000,
    stayType: 'Short',
    roomNumber: 4,
  },
  {
    date: '2026-05-02',
    type: 'INCOME',
    category: 'Bar',
    description: 'Snooker',
    totalCharged: 1500,
    amountPaid: 1500,
    isSnooker: true,
  },
  {
    date: '2026-05-02',
    type: 'EXPENSE',
    category: 'Utilities',
    description: 'Backup Gas',
    totalCharged: 6800,
    amountPaid: 6800,
  },
  {
    date: '2026-05-02',
    type: 'INCOME',
    category: 'Rooms',
    description: 'Lodge Jiro (Night) Room 3',
    totalCharged: 10000,
    amountPaid: 10000,
    stayType: 'Night',
    roomNumber: 3,
  },
  {
    date: '2026-05-02',
    type: 'INCOME',
    category: 'Bar',
    description: '2 Malt 1 Fanta 2 bottle water (Jiro)',
    totalCharged: 4500,
    amountPaid: 0,
  },
  // === May 3, 2026 ===
  {
    date: '2026-05-03',
    type: 'INCOME',
    category: 'Rooms',
    description: 'Lodge Customer 1 (Night) Room 1',
    totalCharged: 15000,
    amountPaid: 15000,
    stayType: 'Night',
    roomNumber: 1,
  },
  {
    date: '2026-05-03',
    type: 'INCOME',
    category: 'Rooms',
    description: 'Lodge Customer 1 (Night) Room 1',
    totalCharged: 15000,
    amountPaid: 5000,
    stayType: 'Night',
    roomNumber: 1,
  },
  {
    date: '2026-05-03',
    type: 'INCOME',
    category: 'Rooms',
    description: 'Lodge Jiro (Night) Room 2',
    totalCharged: 15000,
    amountPaid: 0,
    stayType: 'Night',
    roomNumber: 2,
  },
  {
    date: '2026-05-03',
    type: 'INCOME',
    category: 'Rooms',
    description: 'Lodge Room 3 (Short) Room 3',
    totalCharged: 5000,
    amountPaid: 5000,
    stayType: 'Short',
    roomNumber: 3,
  },
  {
    date: '2026-05-03',
    type: 'INCOME',
    category: 'Rooms',
    description: 'Lodge Let Love Lead (Night) Room 4',
    totalCharged: 8000,
    amountPaid: 0,
    stayType: 'Night',
    roomNumber: 4,
  },
  {
    date: '2026-05-03',
    type: 'INCOME',
    category: 'Rooms',
    description: 'Lodge Captain (Short) Room 5',
    totalCharged: 5000,
    amountPaid: 0,
    stayType: 'Short',
    roomNumber: 5,
  },
  {
    date: '2026-05-03',
    type: 'INCOME',
    category: 'Rooms',
    description: 'Lodge Humble (Night) Room 6',
    totalCharged: 10000,
    amountPaid: 10000,
    stayType: 'Night',
    roomNumber: 6,
  },
  {
    date: '2026-05-03',
    type: 'EXPENSE',
    category: 'Utilities',
    description: 'Gas Cylinder Fill - Generator',
    totalCharged: 15500,
    amountPaid: 15500,
  },
  {
    date: '2026-05-03',
    type: 'INCOME',
    category: 'Bar',
    description: 'Humble Drinks',
    totalCharged: 5000,
    amountPaid: 5000,
  },
];
